version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      # POSTGRES_USER: root
      # POSTGRES_PASSWORD: test
      # POSTGRES_DB: gym_maintainer
    container_name: gym_maintainer_db
    volumes:
      - ./postgres:/var/lib/postgresql/data
  # api:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - 8080:8080
