version: '3'
services:

  mongo:
    image: mongo:5
    container_name: mongo
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
        MONGODB_DATABASE: ${DB_NAME}
        # MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
        # MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mongo:/data/db

  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
  #     ME_CONFIG_MONGODB_URL: mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongo:27017/
