version: '3'
services:
  db:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
        MONGODB_DATABASE: ${DB_NAME}
        MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mongo:/data/db
