name: Deploy Job Step
on: workflow_call
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub Context
        run: echo "${{ toJson(github) }}"
      - name: Checking Environment
        run: echo "${{toJson(env)}}"
      - name: Checking Actual Job
        run: echo "${{toJson(job)}}"
      - name: Dummy Step
        run: echo "This is a dummy step"
