name: Deploy Job Step
on:
  workflow_call:
    inputs:
      artifact_name:
        description: Artifact folder name
        required: true
        default: dist
        type: string
    outputs:
      result:
        description: The result of the job
        value: ${{jobs.deploy.outputs.dist-result}}
jobs:
  deploy:
    outputs:
      dist-result: ${{steps.set_result_output.outputs.step-result}}
    runs-on: ubuntu-latest
    steps:
      - name: Get Main File Name
        id: get_main_file_name
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.artifact_name}}
      - name: List Files
        run: ls -la
      - name: Set Result Output
        id: set_result_output
        run: echo "step-result=success" >> $GITHUB_OUTPUT
      - name: Checking Actual Job
        run: echo "${{toJson(job)}}"
      - name: Dummy Step
        run: echo "This is a dummy step"
